services:
  - type: web
    name: mariela-pdv-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install --include=dev && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: MONGODB_URI
        sync: false
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
      - key: REDIS_URL
        sync: false
